language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support
before_install:
  - chmod +x gradlew
script:
  - ./gradlew assemblecoolapkRelease --stacktrace
